POST http://localhost:5000/v1/contact-form/submit HTTP/1.1
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "john@doe.com",
    "date": "15.06.2024",
    "location": "Großbeeren",
    "time_start": "14:00",
    "time_end": "02:00",
    "type_of_request": "Musik / DJ",
    "message": "Hello, World!"
}

###